### PR TITLE
#433 => https://github.com/docToolchain/docToolchain/issues/433 proposal

### PR DESCRIPTION
**Pull request by ehmkah**
This is a proposal for fixing https://github.com/docToolchain/docToolchain/issues/433

### CODE REVIEW

**Comment by rdmueller** [comment]
hey, this is great!
shouldn't we deploy this image to the doctoolchain-dockerhub space the same way as the other images?

**Comment by ehmkah** [comment]
Yes - because than its "find - and useable" for me and others :-)

Should I remove the buildscript because it contains my docker-hub name? For me those building-scripts are somehow easier to handle than copy-paste from Readme files. 

Or are there any other changes required?

**Comment by rdmueller** [comment]
I think the main missing point is a github action workflow https://github.com/docToolchain/docker-image/tree/ng-beta/.github/workflows

I know these workflows are quite complex and I am currently not sure where to add your image in the workflow.

Any ideas?

**Comment by ehmkah** [comment]
OK - I always wanted to learn something about those git-actions.  It looks like the time has come.

One remaining question for me is whether I could leave the base image as doctoolchain/doctoolchain:v2.1.0 or whether the pandoc step should be added to the alpine image as an extra step.

**Comment by rdmueller** [comment]
good question. you decide!

**Comment by ehmkah** [comment]
i updated my fork so the base doctoolchain is building. I copied the content of the doctoolchain-build and added the pandoc instructions into it. Also there is this github build action. 

I hope this is fine for the moment.

**Comment by rdmueller** [comment]
Great! Let's build the image!

**Comment by ehmkah** [comment]
Thank you also pushing it to docker-hub 

https://hub.docker.com/r/doctoolchain/doctoolchain-with-pandoc

**Comment by rdmueller** [comment]
should we add this somewhere to the docs?

**Comment by ehmkah** [comment]
yes. i am unsure where to put it. https://github.com/docToolchain/docker-image/blob/ng-beta/README.md would be my first choice. That might also be a good starting for describing the differneces between the available images.

Or where is your favorite place?

**Comment by rdmueller** [comment]
I guess the README is a good choice. And we should link to it somewhere from the main docToolchain documentation, shouldn't we?

**Comment by ehmkah** [comment]
https://github.com/docToolchain/docker-image/pull/41 => i am unsure what the jenkins and the azure docker-image are useful for.

**Comment by ehmkah** [comment]
I wanted to link official documentation to this docker-image readme, but i do not see a good place to put. First try was 120_self-contained-dtc.adoc but this is somehow about self containing dtc - any ideas?

**Pull request merged**
